CREATE TABLE users(
    ID SERIAL,
    VERSION bigint NOT NULL,
    USER_NAME VARCHAR(300) NOT NULL,
    PASSWORD VARCHAR(30) NOT NULL,
    MAIL_ADDRESS VARCHAR(200) NOT NULL,
    IS_DELETED BOOLEAN DEFAULT false,
    IS_LOCKED BOOLEAN DEFAULT false,
    PRIMARY KEY (VERSION, MAIL_ADDRESS)
)